name: darwin_web_starter
description: the darwin framework project generator.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  darwin_starter: ^0.0.1-alpha.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_markdown: ^0.6.13
  google_fonts: ^3.0.1
  file_saver: ^0.1.1
  archive: ^3.3.5
  eva_icons_flutter: ^3.1.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
